### ISSUE TITLE
Issues running with typescript

### ISSUE THREAD

**Issue by lstrzebinczyk** [pzuraq/ember-decorators-polyfill#13]
Hello

I have a codebase I've been successfully running with ember-decorators for a while now. I gave it a try to update to this polyfill, but I am receiving errors from typescript:

```
app/services/color-code-manager.ts:67:3 - error TS1240: Unable to resolve signature of property decorator when called as an expression.

67   @service router!: RouterService;
```

```
app/controllers/download-portal.ts:64:13 - error TS2345: Argument of type '"downloadPortal"' is not assignable to parameter of type 'ComputedPropertyCallback<{}>'.

64   @computed("downloadPortal")
```

Those same decorators were (are) properly recognized by typescript when imported from ember-decorators.

Is this a known issue with known solution or roadmap? I can, if needed, provide more details on the issue.

Edit: This happens on @types/ember 3.1.0, which I assume matters here.

**Comment by pzuraq** [comment]
According to #2 the solution is to use the latest version of `@types/ember`, which should be updated to provide the correct typings. If it is not, I would open a bug report over there. This will be an issue in Ember 3.10.0 too.

**Comment by lstrzebinczyk** [comment]
Ok, I got it to not have those specific issues with proper version of types for object and service.
I can't quite get that to run still, but due to issues related to typing specifically. So I am closing this issue, and thank you very much for pointing me to the right direction.

**Comment by lstrzebinczyk** [comment]
FYI: I got everything working nicely and with no problem, once I took the time to upgrade to types 3.1.0 : )

**Comment by pzuraq** [comment]
Awesome, glad to hear!
