### ISSUE TITLE
Runloop decorators?

### ISSUE THREAD

**Issue by Ravenstine** [pzuraq/ember-decorators-polyfill#14]
Is there a plan to polyfill `@ember/runloop`?  Is used to be possible to use `@debounce` with [this](https://github.com/ember-decorators/runloop), but now that project is archived.

**Comment by pzuraq** [comment]
The project was archived because we decided it wasn’t a good idea, I would recommend moving away from those decorators. This polyfill is only for the decorators that went through the Ember RFC process, we will not be adding any more.
