### ISSUE TITLE
Ember Data decorators: An element descriptors .kind property must be either method

### ISSUE THREAD

**Issue by allthesignals** [pzuraq/ember-decorators-polyfill#16]
![image](https://user-images.githubusercontent.com/5004319/57646968-d96bbb00-758f-11e9-89af-bef83256f1cb.png)

Hi, I followed these instructions ^ I installed the polyfill. Now I'm importing the decorators from DS (import DS from 'ember-data'), but I'm seeing a familiar error:

> TypeError: An element descriptor's .kind property must be either "method" or "field", but a decorator created an element descriptor with .kind "undefined"
"ember-decorators-polyfill": "1.0.4", <- this is my polyfil version in devDeps
Ember-data is 3.8

Here's my project branch with 1) models honoring new API and 2) package.json reflecting new deps:

https://github.com/NYCPlanning/labs-applicantmaps/tree/545-deprecation-warnings

**Comment by allthesignals** [comment]
I think this problem is downstream of another deprecation warning concerning removing `/babel-transforms` and upgrading `ember-cli-babel` to at least 7.7.3. Once I did that, the problem was resolved.

Is it worth noting that these things are connected?

**Comment by pzuraq** [comment]
Yes, we should probably mention in the README that you have to be using the stage 1 transforms, and that the recommended way to use the stage 1 transforms is to upgrade `ember-cli-babel` and drop the babel-transforms package.

**Comment by BryanCrotaz** [comment]
note for googlers, it's the `@ember-decorators/babel-transforms` addon that you need to remove

**Comment by pzuraq** [comment]
I'm going to close this issue for now, let me know if you're still having problems! Also thanks @BryanCrotaz for that note 😄
