### ISSUE TITLE
Types

### ISSUE THREAD

**Issue by pzuraq** [pzuraq/ember-decorators-polyfill#2]
How do we polyfill them?

**Comment by dfreeman** [comment]
I saw a little chatter about this in Discord, but I didn't totally follow what needed to be worked out. As long as the consumer is on the latest `@types/ember__object`, using `@computed('dep')` [should 'just work'](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/6f7a141fb85d645316c66eb228f158a3f24513c9/types/ember__object/index.d.ts#L25) with TypeScript.

Can confirm I was pleasantly surprised when I discovered that myself this morning 🙂

**Comment by pzuraq** [comment]
Awesome! I guess this is fixed then 😄
