### ISSUE TITLE
Cannot read property 'attr' of undefined

### ISSUE THREAD

**Issue by bbleungg** [pzuraq/ember-decorators-polyfill#29]
When the `patchDataDecorators` function runs, it cannot find the DS

```javascript
 if (!isFieldDescriptor([target, key, desc])) {
      actionFn = target;
      try {
        DS = mainRequire('ember-data').default;
      } catch (e) {
        return mainRequire(moduleName);
      }

      let decorator = function(target, key, desc) {
        assert(
          'The @action decorator may only be passed a method when used in classic classes. You should decorate methods directly in native classes',
          false
      let {
        attr: dataAttr,
        belongsTo: dataBelongsTo,
        hasMany: dataHasMany,
      } = DS;

      let attr = computedMacroWithOptionalParams(dataAttr);
      let belongsTo = computedMacroWithOptionalParams(dataBelongsTo);
      let hasMany = computedMacroWithOptionalParams(dataHasMany);

      DS.attr = attr;
      DS.belongsTo = belongsTo;
      DS.hasMany = hasMany;
```

Chrome DevTools also logs multiple warnings: `Warning: Library "Ember Data" is already registered with Ember"`

This seems to only be an issue in `^1.1.0` (when `patchDataDecorators` was added)

**Comment by pzuraq** [comment]
This should be fixed when using the latest release. If it is still an issue, please let me know.

**Comment by joshuaswift** [comment]
@pzuraq I'm still getting this error on `1.1.5` unfortunately. I noticed after installing latest version of [ember-sortable](https://github.com/adopted-ember-addons/ember-sortable) which has this polyfill as a dependency, they're on 1.1.1 currently but I tested locally with 1.1.5 and getting this error.
